config/routes.rb
Rails.application.routes.draw do
  resources :colaborators do 
    member do 
      get "otravista"
    end

    collection do 
      get "search"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "colaborators#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborator.rb
class Colaborator < ApplicationRecord
    include PgSearch::Model 

    pg_search_scope :search_full_text,
    against: {
        name: 'A',
        email: 'B',
        id: 'C',
    },
    using: {
        tsearch: {
            prefix: true,      # Coincidencias de prefijo
            any_word: true,    # Coincidencias intermedias
            dictionary: "spanish"  # Diccionario para búsqueda en español (opcional, reemplaza "spanish" según necesites)
        }
    }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 3
    include Pagy::Backend   

    require 'pagy/extras/bootstrap'
    #Pagy::I18n.load(locale: 'es', filepath: 'config/locales/es.yml')
end

app/controllers/colaborators_controller.rb
class ColaboratorsController < ApplicationController
  before_action :set_colaborator, only: %i[ show edit update destroy ]

  

  def otravista
  end
  
  # GET /colaborators or /colaborators.json
  def index
    @pagy, @colaborators = pagy(Colaborator.all.order(:name))

    if params[:query_text].present?
      @pagy, @colaborators = pagy(Colaborator.search_full_text(params[:query_text]))
    end
  end

  # GET /colaborators/1 or /colaborators/1.json
  def show
  end

  # GET /colaborators/new
  def new
    @colaborator = Colaborator.new
  end

  # GET /colaborators/1/edit
  def edit
  end

  # POST /colaborators or /colaborators.json
  def create
    @colaborator = Colaborator.new(colaborator_params)

    respond_to do |format|
      if @colaborator.save
        format.html { redirect_to colaborator_url(@colaborator), notice: "Colaborator was successfully created." }
        format.json { render :show, status: :created, location: @colaborator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaborators/1 or /colaborators/1.json
  def update
    respond_to do |format|
      if @colaborator.update(colaborator_params)
        format.html { redirect_to colaborator_url(@colaborator), notice: "Colaborator was successfully updated." }
        format.json { render :show, status: :ok, location: @colaborator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaborators/1 or /colaborators/1.json
  def destroy
    @colaborator.destroy

    respond_to do |format|
      format.html { redirect_to colaborators_url, notice: "Colaborator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborator
      @colaborator = Colaborator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def colaborator_params
      params.require(:colaborator).permit(:name, :email, :direction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/colaborators_helper.rb
module ColaboratorsHelper
end

app/views/colaborators/_colaborator.html.erb
<div id="<%= dom_id colaborator %>">
    <tr>
      <td><%= colaborator.id %></td>
      <td><%= colaborator.name %></td>
      <td><%= colaborator.email %></td>
      <td><%= colaborator.direction %></td>
      <td><%= link_to "Mostrar este colaborador", colaborator %></td>
    </tr>
</div>

app/views/colaborators/_form.html.erb
<%= form_with model: colaborator  do |form| %>
  <% if colaborator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(colaborator.errors.count, "error") %> prohibited this colaborator from being saved:</h2>

      <ul>
        <% colaborator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :direction, style: "display: block" %>
    <%= form.text_field :direction %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colaborators/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/colaborators/edit.html.erb
<h1>Editing colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Show this colaborator", @colaborator %> |
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/index.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with url: colaborators_path, method: :get do |form| %>
  <%= form.text_field :query_text, placeholder: 'Escribe AQUI', value: params[:query_text] %>
  <%= form.submit "Buscar..." %>
<% end %>

<h1>Colaborators</h1>

<div id="colaborators">
  <table border="1" class="table">
    <thead class="table-dark">
      <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>EMAIL</th>
        <th>DIRECTION</th>
        <th>Mostrar</th>
      <tr>
    </thead>
    <% @colaborators.each do |colaborator| %>
      <%= render colaborator %>
    <% end %>
  </table>
</div>

<%== pagy_bootstrap_nav(@pagy) %>



<%= link_to "Agregar Colaborador", new_colaborator_path %>

app/views/colaborators/new.html.erb
<h1>New colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/otravista.html.erb
<%= Colaborator.find(params["id"]).name %>

app/views/colaborators/search.html.erb
<% Colaborator.all.each do |x| %>
    <%= x.name %> <br>
    <hr>
<% end %>

app/views/colaborators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @colaborator %>

<div>
  <%= link_to "Edit this colaborator", edit_colaborator_path(@colaborator) %> |
  <%= link_to "Back to colaborators", colaborators_path %>

  <%= button_to "Destroy this colaborator", @colaborator, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TareaRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" />
  </head>

  <body>
    <%= render "navbar" %>

    <div class="container p-5">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>